### PR TITLE
running server using uvicorn + loading env variables using .env

### PR DESCRIPTION
**Pull request by krrishdholakia**
i ran `python main.py` but the server didn't run. So i added support for this functionality using uvicorn. 

I also noticed when I set the AUTH_TOKEN in my .env, it didn't get read in `get_env()`, so I added support for that by using python-dotenv to load the env variables - https://pypi.org/project/python-dotenv/

### CODE REVIEW

**Comment by krrishdholakia** [comment]
adding additional api key options in the .env template

**Comment by krrishdholakia** [comment]
Exposed a new endpoint - `/generate_key` -> this should enable dynamic auth token generation 

It then writes the generated auth token to the 'AUTH_TOKEN` .env variable. This means, the next time a request is made with that token, it is now accepted by the proxy server. 

Screenshot 2023-09-09 at 12 17 25 PM

**Comment by yujonglee** [comment]
Looks good. Please take a look at #2 since there's big change in project structure.

**Comment by krrishdholakia** [comment]
lgtm

**Pull request closed without merging**
